name: Discord Push Notification

on:
  push:
    branches:
      - main  # or your branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build and send Discord message
        run: |
          commits=$(echo "${{ toJson(github.event.commits) }}" | jq -r '.[] | "- [`" + .id[0:7] + "`] " + .message + " (by " + .author.name + ")"')
          content="**${{ github.actor }}** pushed to **${{ github.repository }}**:\n$commits"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(jq -nc --arg content "$content" '{content: $content}')" \
               ${{ secrets.DISCORD_WEBHOOK }}
