name: Discord Push Notification

on:
  push:
    branches:
      - main  # or your branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification to Discord
        run: |
          commits=$(echo "${{ github.event.commits[*].message }}" | jq -R -s '. | gsub("\\n"; "")')
          message="**${{ github.actor }}** pushed to **${{ github.repository }}**:\n$commits"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": $commits}" \
               ${{ secrets.DISCORD_WEBHOOK }}
